<strong>{{screenLockPassCodeLength}}</strong> digits passcode is set.: <strong>{{screenLockPassCodeLength}}</strong> chiffres d√©finis
Activation Success: Activation r√©ussie
? Add a star to the copied text when you copy it twice within 1 second. This allows you to quickly add copied text or links to your favorites and easily find it in the clipboard history.
: Ajouter une √©toile au texte copi√© deux fois en 1 seconde. Cela permet d'ajouter rapidement du texte ou des liens aux favoris et de les retrouver facilement dans l'historique du presse-papiers.
Add an unlimited number of tabs within each collection for better organization and easy access.: Ajoutez un nombre illimit√© d'onglets dans chaque collection pour une meilleure organisation et un acc√®s facile.
'Add an unlimited number of tabs within each collection for better organization and easy access.                                ': 'Ajoutez un nombre illimit√© d''onglets dans chaque collection pour une meilleure organisation et un acc√®s facile.                                '
Advanced settings: Param√®tres avanc√©s
Already Active: D√©j√† actif
Application Auto Start: D√©marrage auto
Application Color Theme: Th√®me couleur app
Application UI Color Theme: Th√®me couleur UI
Application UI Fonts Scale: √âchelle police UI
Application UI Language: Langue UI
Applications listed below will not have their copy to clipboard action captured in clipboard history. Case insensitive.: Les applications ci-dessous n'auront pas leur action de copie captur√©e dans l'historique. Insensible √† la casse.
Auto Disable History Capture when Screen Unlocked: D√©sactiver auto capture historique √† l'√©cran d√©verrouill√©
Auto Lock Application Screen on User Inactivity: Verrouillage auto √©cran sur inactivit√©
Auto Lock Screen on User Inactivity: Verrouillage auto sur inactivit√©
Auto Lock the Screen on User Inactivity: Verrouillage auto √©cran sur inactivit√©
Auto Masking Words List: Liste mots masqu√©s auto
Auto update on capture: Mise √† jour auto √† la capture
Auto-Clear Settings: Param√®tres nettoyage auto
Auto-Generate Link Card Preview: G√©n√©rer auto aper√ßu carte lien
Auto-Preview Link on Hover: Aper√ßu auto lien au survol
Auto-Star on Double Copy: √âtoile auto double copie
Auto-Update on Capture: Mise √† jour auto √† la capture
Auto-delete clipboard history after: Supprimer auto historique apr√®s
? Automatically create link card preview in the clipboard history. This allows to quickly view website details without opening or pasting the link.
: Cr√©er auto un aper√ßu carte lien dans l'historique. Permet de voir rapidement les d√©tails du site sans ouvrir ou coller le lien.
Back: Retour
Capture History: Capturer historique
Change the application UI font size scale: Modifier l'√©chelle de taille de police UI
Change the application UI language: Changer la langue UI de l'application
Change the application user interface color theme: Changer le th√®me couleur de l'interface
Change the application user interface font size scale: Modifier l'√©chelle de taille de police UI
Change the application user interface language: Changer la langue de l'interface
Clip Notes Popup Maximum Dimensions: Dimensions max popup notes clip
Clipboard History Settings: Param√®tres historique presse-papiers
'Complete details:': 'D√©tails complets :'
Configure settings to automatically delete clipboard history items after a specified duration.: Configurer la suppression auto des √©l√©ments d'historique apr√®s une dur√©e sp√©cifi√©e.
Create a preview card on link hover in the clipboard history. This allows you to preview the link before opening or pasting it.: Cr√©er une carte d'aper√ßu au survol du lien dans l'historique. Permet de pr√©visualiser le lien avant de l'ouvrir ou de le coller.
Create an unlimited number of collections to organize your clips and menus.: Cr√©ez un nombre illimit√© de collections pour organiser vos clips et menus.
Custom: Personnalis√©
Custom themes: Th√®mes perso
Decrease UI Font Size: R√©duire taille police
? Display clipboard history capture toggle on the locked application screen. This allows you to control history capture settings directly from the lock screen.
: Afficher le bouton de capture d'historique sur l'√©cran verrouill√©. Permet de contr√¥ler les param√®tres de capture directement depuis l'√©cran de verrouillage.
Display disabled collections name on the navigation bar collections menu: Afficher noms collections d√©sactiv√©es dans menu collections barre nav
Display disabled collections name on the navigation bar under collections menu: Afficher noms collections d√©sactiv√©es sous menu collections barre nav
Display full name of selected collection on the navigation bar: Afficher nom complet collection s√©lectionn√©e sur barre nav
Drag and drop to prioritize languages for detection. The higher a language is in the list, the higher its detection priority.: Glisser-d√©poser pour prioriser les langues. Plus une langue est haute, plus sa priorit√© de d√©tection est √©lev√©e.
Email: Email
Email is not valid: Email non valide
'Email:': 'Email :'
Emails do not match: Emails ne correspondent pas
Enable Auto Start: Activer d√©marrage auto
Enable Clip Title Hover Show with Delay: Activer affichage titre clip au survol avec d√©lai
Enable application auto start on system boot: Activer d√©marrage auto de l'app au d√©marrage syst√®me
Enable auto lock the application screen after a certain period of inactivity, to prevent unauthorized access to your data.: Activer verrouillage auto de l'√©cran apr√®s inactivit√© pour pr√©venir acc√®s non autoris√© aux donn√©es.
Enable auto lock the application screen when user not active: Activer verrouillage auto √©cran si utilisateur inactif
Enable auto update on capture: Activer mise √† jour auto √† la capture
Enable history capture: Activer capture historique
Enable programming language detection: Activer d√©tection langage programmation
Enable screen unlock requirement on app launch for enhanced security, safeguarding data from unauthorized access.: Activer d√©verrouillage √©cran au lancement pour s√©curit√© accrue, prot√©geant les donn√©es d'acc√®s non autoris√©s.
Enhance security by automatically locking the application screen after a set period of user inactivity.: Renforcer la s√©curit√© en verrouillant auto l'√©cran apr√®s une p√©riode d'inactivit√© d√©finie.
Enter Passcode length: Entrer longueur code
Enter recovery password to reset passcode.: Entrer mot de passe r√©cup√©ration pour r√©initialiser code.
Enter your <strong>{{screenLockPassCodeLength}} digits</strong> passcode: Entrez votre code √† <strong>{{screenLockPassCodeLength}} chiffres</strong>
Entered Passcode is invalid: Code saisi non valide
Excluded Apps List: Liste apps exclues
Execute Web Requests: Ex√©cuter requ√™tes web
Execute terminal or shell commands directly from PasteBar clip and copy the results to the clipboard.: Ex√©cuter commandes terminal directement depuis clip PasteBar et copier r√©sultats dans presse-papiers.
'Expires:': 'Expire le :'
Forgot Passcode ? Enter your recovery password to reset the passcode.: Oubli√© code ? Entrez mot de passe r√©cup√©ration pour r√©initialiser.
Forgot passcode ?: Oubli√© code ?
Forgot?: Oubli√© ?
Forgot? Reset using Password: Oubli√© ? R√©initialiser avec mot de passe
Get priority email support from us to resolve any issues or questions you may have about PasteBar.: Obtenez un support email prioritaire pour r√©soudre vos probl√®mes ou questions sur PasteBar.
'Hint: {{screenLockRecoveryPasswordMasked}}': 'Indice : {{screenLockRecoveryPasswordMasked}}'
Incorrect passcode.: Code incorrect.
Increase UI Font Size: Augmenter taille police
Issued: √âmis
Large: Grand
List each application name or window identifier on a new line.: Listez chaque nom d'application ou identifiant de fen√™tre sur une nouvelle ligne.
List each word or sentence on a new line.: Listez chaque mot ou phrase sur une nouvelle ligne.
Lock Screen Clipboard History Capture Control: Contr√¥le capture historique presse-papiers √©cran verrouill√©
Lock Screen PassCode: Code √©cran verrouill√©
Lock Screen Passcode: Code √©cran verrouill√©
Manage Collections: G√©rer collections
Maximum 10 digits: Maximum 10 chiffres
Maximum devices: Appareils maximum
Medium: Moyen
Minimal 4 digits: Minimum 4 chiffres
Minimize Window: R√©duire fen√™tre
Minimum number of lines to trigger detection: Nombre min lignes pour d√©clencher d√©tection
Name: Nom
Open Security Settings: Ouvrir param√®tres s√©curit√©
Passcode digits remaining: Chiffres restants du code
Passcode is locked.: Code verrouill√©.
Passcode is not set: Code non d√©fini
Passcode is not valid: Code non valide
Passcode length: Longueur du code
Passcode mismatch: Codes ne correspondent pas
Passcode reset is locked.: R√©initialisation code verrouill√©e.
Passcode successfully verified: Code v√©rifi√© avec succ√®s
Passcode verification error: Erreur v√©rification code
Passcode verification is locked.: V√©rification code verrouill√©e.
Password is incorrect.: Mot de passe incorrect.
Password is incorrect. <br/>{{screenLockRecoveryPasswordMasked}}: Mot de passe incorrect. <br/>{{screenLockRecoveryPasswordMasked}}
'Password is incorrect. Hint: {{screenLockRecoveryPasswordMasked}}': 'Mot de passe incorrect. Indice : {{screenLockRecoveryPasswordMasked}}'
'Password is incorrect. Masked password is: {{screenLockRecoveryPasswordMasked}}': 'Mot de passe incorrect. Mot de passe masqu√© : {{screenLockRecoveryPasswordMasked}}'
Password is incorrect. {{screenLockRecoveryPasswordMasked}}: Mot de passe incorrect. {{screenLockRecoveryPasswordMasked}}
Passwords do not match: Mots de passe ne correspondent pas
PasteBar Settings: Param√®tres PasteBar
Pin Window: √âpingler fen√™tre
Pin on Top Window: √âpingler en haut
Please set up a Passcode and recovery password in Security Settings to enable Screen Lock and ensure better security.: Configurez un code et un mot de passe de r√©cup√©ration dans Param√®tres de s√©curit√© pour activer le verrouillage d'√©cran et assurer une meilleure s√©curit√©.
Please try again: Veuillez r√©essayer
Preview current popup size on hover.: Aper√ßu taille popup actuelle au survol.
Prioritize Language Detection: Prioriser d√©tection langue
Priority support: Support prioritaire
Programming Language Detection: D√©tection langage programmation
Programming Language Selection: S√©lection langage programmation
Protect your data by requiring screen unlock authentication whenever the application starts.: Prot√©gez vos donn√©es en exigeant l'authentification au d√©marrage de l'application.
Recovery Password for Lock Screen Passcode: Mot de passe r√©cup√©ration pour code √©cran verrouill√©
Recovery password is set.: Mot de passe r√©cup√©ration d√©fini.
Refresh Application UI: Actualiser UI application
Refresh UI: Actualiser UI
Require Screen Unlock at Application Start: D√©verrouillage √©cran requis au d√©marrage
? Require screen unlock at application launch to enhance security. This setting ensures that only authorized users can access the application, protecting your data from unauthorized access right from the start.
: Exiger le d√©verrouillage de l'√©cran au lancement pour renforcer la s√©curit√©. Assure que seuls les utilisateurs autoris√©s acc√®dent √† l'application, prot√©geant vos donn√©es d√®s le d√©part.
Reset Font Size: R√©initialiser taille police
Run Terminal or Shell Commands: Ex√©cuter commandes terminal/shell
Scrape and parse websites or API responses using built-in web scraping tools and copy the extracted data to the clipboard.: Extraire et analyser sites web ou r√©ponses API avec outils int√©gr√©s et copier les donn√©es extraites dans le presse-papiers.
? 'Scrape and parse websites or API responses using built-in web scraping tools and copy the extracted data to the clipboard.                                '
: 'Extraire et analyser sites web ou r√©ponses API avec outils int√©gr√©s et copier les donn√©es extraites dans le presse-papiers.                                '
Security: S√©curit√©
Security Settings: Param√®tres de s√©curit√©
Send HTTP requests to web APIs or services and copy the response data to the clipboard.: Envoyer requ√™tes HTTP aux APIs/services web et copier les donn√©es de r√©ponse dans le presse-papiers.
Sensitive words or sentences listed below will automatically be masked if found in the copied text. Case insensitive.: Les mots/phrases sensibles list√©s seront masqu√©s si trouv√©s dans le texte copi√©. Insensible √† la casse.
Set a passcode to unlock the locked screen and protect your data from unauthorized access.: D√©finir un code pour d√©verrouiller l'√©cran et prot√©ger vos donn√©es des acc√®s non autoris√©s.
? Set a recovery password to easily reset your lock screen passcode if forgotten. Your password will be securely stored in your device's OS storage.
: D√©finir un mot de passe de r√©cup√©ration pour r√©initialiser le code d'√©cran si oubli√©. Stock√© en s√©curit√© dans l'OS de votre appareil.
Settings: Param√®tres
Show Clipboard History Capture Control on Lock Screen: Afficher contr√¥le capture historique sur √©cran verrouill√©
Show Disable History Capture When Screen Locked: Afficher d√©sactivation capture historique si √©cran verrouill√©
Show Disabled Collections: Afficher collections d√©sactiv√©es
? Show clipboard history capture toggle when the application screen is locked. This allow you to control capturing history settings from the application locked screen.
: Afficher bascule capture historique sur √©cran verrouill√©. Permet de contr√¥ler les param√®tres de capture depuis l'√©cran verrouill√©.
Show collection name on the navbar: Afficher nom collection dans navbar
Show disabled collections on the navbar list: Afficher collections d√©sactiv√©es dans liste navbar
Skip auto start prompt on app launch: Ignorer invite d√©marrage auto au lancement
Small: Petit
Stop Words List: Liste de mots √† ignorer
Swap Panels Layout: Inverser disposition panneaux
Switch the layout position of panels in Clipboard History and Paste Menu views: Inverser position des panneaux dans vues Historique et Menu Collage
Thank you again for using PasteBar.: Merci encore d'utiliser PasteBar.
Thank you for testing! üôå: Merci pour le test ! üôå
? This option lets you control the display and timing of hover notes on clips. You can choose to show notes instantly or with a delay to prevent unintended popups.
: Cette option contr√¥le l'affichage des notes au survol des clips. Choisissez affichage instantan√© ou diff√©r√© pour √©viter les popups non d√©sir√©s.
? This option lets you customize the maximum width and height of the popup that displays clip notes, ensuring it fits comfortably within your desired size.
: Cette option permet de personnaliser la largeur/hauteur max du popup des notes de clip, assurant qu'il s'adapte √† la taille souhait√©e.
To downgrade your current version, please visit: Pour r√©trograder votre version actuelle, visitez
'To downgrade, please visit: ': 'Pour r√©trograder, visitez : '
To ensure the best detection accuracy, please select up to 7 languages. Limiting choices improves precision.: Pour une d√©tection optimale, s√©lectionnez jusqu'√† 7 langues. Limiter les choix am√©liore la pr√©cision.
Today: Aujourd'hui
Tomorrow: Demain
Try after <strong>{{resetPassCodeNextDelay}}</strong> seconds: R√©essayez dans <strong>{{resetPassCodeNextDelay}}</strong> secondes
Try again after <strong>{{resetPassCodeNextDelay}}</strong> seconds: R√©essayez dans <strong>{{resetPassCodeNextDelay}}</strong> secondes
UI Language: Langue de l'interface
UnPin Window: D√©tacher fen√™tre
Unlimited Collections: Collections illimit√©es
Unlimited Tabs per Collection: Onglets illimit√©s par collection
Unlimited paste history: Historique de collage illimit√©
Use Password: Utiliser mot de passe
User Preferences: Pr√©f√©rences utilisateur
Web Scraping and Parsing: Extraction et analyse web
Words or sentences listed below will not be captured in clipboard history if found in the copied text. Case insensitive.: Mots/phrases list√©s non captur√©s dans l'historique si trouv√©s dans le texte copi√©. Insensible √† la casse.
passcode reset: r√©initialisation code
password reset: r√©initialisation mot de passe